networks:
  database-network:
    driver: bridge

volumes:
  user-identity-provider-database-dev: {}

services:
  user-identity-provider-db-dev:
    container_name: user-idp-db-dev
    image: bitnami/postgresql:15.2.0
    environment:
      POSTGRESQL_DATABASE: dev
      POSTGRESQL_USER: postgresql
      POSTGRESQL_PASSWORD: dev_password
    volumes:
      - user-identity-provider-database-dev:/bitnami/postgresql
    networks:
      - database-network
    ports:
      - "5432:5432"