server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: dev-resource
          uri: lb://DEV-RESOURCE-SERVER-1/
          predicates:
            - Path=/resource/**
          filters:
            - RewritePath=/resource/?(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie

  security:
    oauth2:
      client:
        registration:
          dev-client:
            provider: spring-idp
            client-id: dev-client
            client-secret: dev
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile, user.read, user.write
        provider:
          spring-idp:
            issuer-uri: http://localhost:9000

eureka:
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

gateway:
  cors:
    configs:
      - mapping-pattern: /**
        allowed-origin-patterns:
          - http://localhost:9000
        allow-credentials: true
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        allowed-headers:
          - Authorization
        max-age: 3600
