server:
  port: 8091

spring:
  application:
    name: dev-resource-server-1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

eureka:
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

resourceserver:
  cors:
    configs:
      - mapping-pattern: /**
        allowed-origin-patterns:
          - http://localhost:8080
          - http://localhost:9000
        allow-credentials: true
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        allowed-headers:
          - Authorization
        max-age: 3600
