server:
  port: 9000

spring:
  application:
    name: authorization-server

  datasource:
    url: jdbc:postgresql://localhost:5432/postgre-dev
    username: dev-user
    password: dev-password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000 # specifies the max time driver will wait for connection from cp
      maximum-pool-size: 10 # max cp size
      minimum-idle: 10 # minimal amount of idling connections
      initialization-fail-timeout: 1 # time required to establish initial connection
      leak-detection-threshold: 0 # time allowed for connection to be outside the cp
      pool-name: hikari-pool-auth-service # cp name
      register-mbeans: true # enabling jmx beans for monitoring purposes

  flyway:
    locations:
      - classpath:db/{vendor}/common
      - classpath:db/{vendor}/dev

  security:
    keys:
      rsa:
        - id: "dev-key"
          private-key: "classpath:dev_rsa.key"
          public-key: "classpath:dev_rsa.pub"

eureka:
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

authorizationserver:
  cors:
    configs:
      - mapping-pattern: /**
        allowed-origin-patterns:
          - http://localhost:8080
        allow-credentials: true
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        allowed-headers:
          - Authorization
        max-age: 3600