server:
  port: 9000

spring:
  application:
    name: authorization-server

  security:
    keys:
      rsa:
        - id: "dev-key"
          private-key: "classpath:dev_rsa.key"
          public-key: "classpath:dev_rsa.pub"

eureka:
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
